import { atom } from 'recoil';

export type ModeValue = null | 'alone' | 'together';

export const selectedModeState = atom<ModeValue>({
  key: 'modeState',
  default: null,
});

export const allModeStates = atom({
  key: 'allModeStates',
  default: {
    alone: new Set([
      '클라이밍',
      '스크린골프',
      'PC방',
      '수영장',
      '공원',
      '도시근린공원',
      '오락실',
      '테마카페',
      '테마파크',
      '복합문화공간',
      '공연장',
      '전시관',
      '도서관',
      '북카페',
      '식물원',
      '백화점',
      '코인노래방',
      '롤러',
      '인라인스케이트장',
      '라이브카페',
    ]),
    together: new Set([
      '당구장',
      '클라이밍',
      '스크린골프',
      'PC방',
      '수영장',
      '스포츠',
      '레저',
      '볼링장',
      '공원',
      '도시근린공원',
      '오락실',
      '보드카페',
      '방탈출카페',
      '테마카페',
      '테마파크',
      '복합문화공간',
      '공연장',
      '관람',
      '체험',
      '전시관',
      '도서관',
      '북카페',
      '미술',
      '공예',
      '식물원',
      '고궁',
      '궁',
      '백화점',
      '스포츠의류',
      '코인노래방',
      '서바이벌게임',
      '롤러',
      '인라인스케이트장',
      '라이브카페',
      '농구장',
    ]),
  },
});
